// Assemble ./dist for the Cloudflare Worker: the page, game data, shared modules,
// the browser copy of the match (/engine and /sim), and /data.js. Bulk art stays
// out; data/asset-index.json tells the browser where to fetch it.

import { cp, mkdir, readdir, readFile, rm, stat, writeFile, copyFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');

// Same module the Node server serves at /data.js (server/index.js DATA_SHIM_JS).
const DATA_SHIM = `// Generated by tools/build-worker.mjs — browser stand-in for server/data.js.
// The simulation's content modules (/sim/content/support/index.js) import getData() from here.
import { getSimData } from './sim/simdata.js';
export function getData() { return getSimData() || {}; }
export function resetData() {}
`;

/**
 * @param {string} src
 * @param {string} dest
 * @param {(rel: string) => boolean} keep
 */
async function copyFiltered(src, dest, keep) {
  async function walk(dir, rel) {
    for (const name of await readdir(dir)) {
      const next = rel ? `${rel}/${name}` : name;
      const abs = path.join(dir, name);
      const st = await stat(abs);
      if (!keep(next, st.isDirectory())) continue;
      const out = path.join(dest, next);
      if (st.isDirectory()) {
        await mkdir(out, { recursive: true });
        await walk(abs, next);
      } else {
        await mkdir(path.dirname(out), { recursive: true });
        await copyFile(abs, out);
      }
    }
  }
  await mkdir(dest, { recursive: true });
  await walk(src, '');
}

async function ensureFonts() {
  const css = path.join(ROOT, 'public', 'fonts', 'fonts.css');
  if (existsSync(css)) return;
  try {
    const { Downloader } = await import('./assets/downloader.mjs');
    const { fontJobs, buildFonts } = await import('./assets/fonts.mjs');
    const dir = path.join(ROOT, 'public', 'fonts');
    const dl = new Downloader({
      root: dir,
      ledgerPath: path.join(ROOT, '.cache', 'fonts-ledger.json'),
      concurrency: 4,
      log: console.log,
    });
    await dl.loadLedger();
    await dl.run(fontJobs(), 'fonts');
    const built = await buildFonts(dir, console.log);
    for (const err of built.errors) console.warn(`[build-worker] font: ${err}`);
  } catch (err) {
    console.warn(`[build-worker] 字体未放进站点（页面会用系统字体）：${err instanceof Error ? err.message : err}`);
  }
}

async function main() {
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });
  await ensureFonts();

  await copyFiltered(path.join(ROOT, 'public'), DIST, (rel) => rel !== 'assets' && !rel.startsWith('assets/'));

  const dataOut = path.join(DIST, 'data');
  await mkdir(dataOut, { recursive: true });
  for (const name of await readdir(path.join(ROOT, 'data'))) {
    if (!name.endsWith('.json') || name === 'local-assets.json') continue;
    await copyFile(path.join(ROOT, 'data', name), path.join(dataOut, name));
  }

  await copyFiltered(path.join(ROOT, 'shared'), path.join(DIST, 'shared'), () => true);

  await copyFiltered(path.join(ROOT, 'server'), path.join(DIST, 'engine'), (rel, isDir) => {
    if (isDir) return true;
    if (!rel.endsWith('.js')) return false;
    if (rel === 'index.js') return false;
    if (rel.toLowerCase() === 'sim/nodedata.js') return false;
    return true;
  });
  await cp(path.join(DIST, 'engine', 'sim'), path.join(DIST, 'sim'), { recursive: true });
  await writeFile(path.join(DIST, 'data.js'), DATA_SHIM);

  if (!existsSync(path.join(ROOT, 'data', 'asset-index.json'))) {
    console.warn('[build-worker] 没有 data/asset-index.json。先在有素材的机器上运行 node tools/build-asset-index.mjs');
  }

  const indexHtml = await readFile(path.join(DIST, 'index.html'), 'utf8');
  if (!indexHtml.includes('/js/main.js') || !existsSync(path.join(DIST, 'engine', 'lobby.js'))) {
    throw new Error('dist 不完整');
  }
  if (!existsSync(path.join(DIST, 'sim', 'simdata.js')) || !existsSync(path.join(DIST, 'shared', 'constants.js'))) {
    throw new Error('dist 缺少 /sim 或 /shared');
  }
  // A new file each build. Wrangler otherwise tells Cloudflare "no asset changed"
  // and the new version keeps serving the previous pages.
  const stamp = new Date().toISOString();
  await writeFile(path.join(DIST, 'build.txt'), `stronghold-protocol ${stamp}\n`);
  console.log(`[build-worker] ${DIST} (${stamp})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
